### ISSUE TITLE
New Business Rule Required

### ISSUE THREAD

**Issue by cmonsalvec** [chjoguer/ISII-WORKSHOPS-FAMILY#1]
Dear developers,

Based on the impact of the pandemic in the 2020 results, the board of the company has approved a new business rule beginning january 2021: If the customer is male, over 25 and younger than 45 then it is needed to subtract $100 from the base premium.

Therefore, we ask you to modify the premium calculation adding this new rule.

Best regards,

**Comment by chjoguer** [comment]
New rule accepted

**Comment by chjoguer** [comment]
Proceeded to categorize the issue

**Comment by chjoguer** [comment]
issue assigned, @Leomk1998 will be the analyst, @chjoguer will develop the solution, @luiacarr will perfom the tests

**Comment by Leomk1998** [comment]
Dear @cmonsalvec, attached below the impact analysis:


#1 
**Impact Analysis:**

The computational resources that will be needed to resolve this issue are: a computer with **Java 8.0+ that supports Eclipse IDE and Github as versioning software.**

Also, the requirements specifications needs a change, so we need a new validation of customer’s age to substract $100 from his base prime. **This change will impact other validations that has a similar age range of costumers.** 

Due to mockups, database and design don´t need to be changed the time to add this new requirement is 1 day and to test this code, we need 1 more day to verificate that these changes doesn´t have confflicts with existing requirements, it means that this new changes in the software, **will be avaliable from 21/01/2021**.



I am looking forward to your confirmation, thanks!

**Comment by chjoguer** [comment]
Isuue resolved 
you can check the solution with the next link:https://github.com/Leomk1998/ISII-WORKSHOPS-FAMILY/blob/c1e030df312dce2294c16a63f8e4096ed80edcdd/ec.edu.espol.workshops.second/src/main/java/ec/edu/espol/workshops/second/CarInsurance.java#L6-L22

**Comment by chjoguer** [comment]
Test Plan and our solution pass all the test, following the document @cmonsalvec , @Leomk1998 ,@luiacarr
https://github.com/Leomk1998/ISII-WORKSHOPS-FAMILY/blob/Issues_Management/Test%20Plan.pdf

**Comment by chjoguer** [comment]
@cmonsalvec , we send the acceptance_test https://github.com/Leomk1998/ISII-WORKSHOPS-FAMILY/blob/Issues_Management/Test%20Plan.pdf, we are wating for any recomendations or your approval. @Leomk1998 @luiacarr

**Comment by cmonsalvec** [comment]
Dear @Leomk1998, I agree with the time and resources you estimated for implementing this feature in your impact analysis.

Dear @chjoguer , I am not a tech guy, so I can't review your code. However, I can check the tests analysis, the test cases and their results. I am happy to know all the tests passed. Excelent job.

Based on that, I do accept the solution, I am looking forward announcing in our company that the new feature is already available.

**Comment by chjoguer** [comment]
We proceed to release the new version of software @Leomk1998

**Comment by chjoguer** [comment]
Dear @cmonsalvec , for use the new software version you should download the project with the following link: https://github.com/Leomk1998/ISII-WORKSHOPS-FAMILY/blob/Issues_Management/realese1.jar, and the next step is have installed javase for execute the project, finally use the next command 'java -jar realese1.jar' and now you can use the new version of software

**Comment by cmonsalvec** [comment]
Thanks @chjoguer we will proceed as informed.

Best regards

**Comment by Leomk1998** [comment]
Dear @cmonsalvec , we will expect your response about the use of the solution and If all is ok, we will close the issue.

**Comment by cmonsalvec** [comment]
Dear @Leomk1998 

Thanks for your concern. So far everything is working fine, and my organization is happy with the new feature.

Regards,

**Comment by chjoguer** [comment]
we are glad to have worked in your organization
Best Regards
